In [ ]:
#Consider the below code to answer further questions:

import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_)


In [4]:
'''Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of
 both the variables.'''


'''The variable list_ is of type list ans the variable array_list if of type numpy.ndarray.'''

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [8]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.T

for i in list_:
    print(type(i))

print('\n')

for j in array_list:
    print(type(j))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
'''3. Considering the following changes in the variable, array_list:'''

array_list = np.array(object = list_, dtype = int)

'''Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types
of each and every element present in both the variables, list_ and array_list.'''


'''Yes, there will be difference in the data type of elements in array_list but not in list.'''

for i in list_:
    print(type(i))

print('\n')

for j in array_list:
    print(type(j))



<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [12]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [16]:
#Q4. Write a code to find the following characteristics of variable, num_array:

#(i) shape

print(f'Shape:{num_array.shape}')

#(ii) size
print(f'Size: {num_array.size}')


Shape:(2, 3)
Size: 6


In [19]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

a = np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions.

idm = np.eye(5)
print(idm)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
